### ISSUE TITLE
Error: Incorrect arguments to mysqld_stmt_execute

### ISSUE THREAD

**Issue by vnc5** [felixfbecker/node-sql-template-strings#9]
Executing:
```javascript
sql.execute(SQL`
        SELECT id, name
        FROM account
        LEFT JOIN login ON login.account_id = account.id
        WHERE login.account_id=${buffer.readInt32BE(0)} AND login.secret=UNHEX(${buffer.toString('hex', 4)}) LIMIT 1`)
```
yields:
```
Error: Incorrect arguments to mysqld_stmt_execute
    at Packet.asError (\node_modules\mysql2\lib\packets\packet.js:543:13)
    at Execute.Command.execute (\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (\node_modules\mysql2\lib\connection.js:261:28)
    at PacketParser.onPacket (\node_modules\mysql2\lib\connection.js:95:66)
    at PacketParser.executeStart (\node_modules\mysql2\lib\packet_parser.js:44:12)
    at Socket.<anonymous> (\node_modules\mysql2\lib\connection.js:97:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20) code: 'ER_WRONG_ARGUMENTS', errno: 1210, sqlState: '#HY000'
```
This works:
```javascript
sql.execute(`
        SELECT id, name
        FROM account
        LEFT JOIN login ON login.account_id = account.id
        WHERE login.account_id=? AND login.secret=UNHEX(?) LIMIT 1`, [buffer.readInt32BE(0), buffer.toString('hex', 4)])
```
I'm using mysql2/promise and MariaDB.

**Comment by felixfbecker** [comment]
Hi, what is the output when you do
```js
console.log(SQL`
        SELECT id, name
        FROM account
        LEFT JOIN login ON login.account_id = account.id
        WHERE login.account_id=${buffer.readInt32BE(0)} AND login.secret=UNHEX(${buffer.toString('hex', 4)}) LIMIT 1`)
```
?

**Comment by vnc5** [comment]
```
SQLStatement {
  strings:
   [ '\n        SELECT id, name\n        FROM account\n        LEFT JOIN login ON login.account_id = account.id\n        WHERE login.account_id=',
     ' AND login.secret=UNHEX(',
     ') LIMIT 1' ],
  values: [ 12, 'ee926e1bb3c53a574cdc776845d5478e8f3a39c6' ] }
```

**Comment by felixfbecker** [comment]
ah sorry, the non-enumerable properties are not included. Could you please do
```js
console.log(require('util').inspect(SQL`...`, {showHidden: true}))
```

**Comment by felixfbecker** [comment]
And on what version are you?

**Comment by vnc5** [comment]
```
SQLStatement {
  strings:
   [ '\n        SELECT id, name\n        FROM account\n        LEFT JOIN login ON login.account_id = account.id\n        WHERE login.account_id=',
     ' AND login.secret=UNHEX(',
     ') LIMIT 1',
     [length]: 3 ],
  values: [ 12, 'ee926e1bb3c53a574cdc776845d5478e8f3a39c6', [length]: 2 ] }
```

Version 2.2.0

**Comment by vnc5** [comment]
I should mention that calling `sql.query` instead of `sql.execute` works. But mysql2 won't execute this as a prepared statement then.

**Comment by felixfbecker** [comment]
That did not do the trick, could you just log `console.log(SQL`...`.sql)`?

**Comment by vnc5** [comment]
```
'\n        SELECT id, name\n        FROM account\n        LEFT JOIN login ON login.account_id = account.id\n        WHERE login.account_id=? AND login.secret=UNHEX(?) LIMIT 1'
```

**Comment by felixfbecker** [comment]
But that seems to be correct... Does it work if you run the query like this
```js
sql.execute({sql: '...', values: [...]})
```
?

**Comment by vnc5** [comment]
Same error with .execute but works with .query

**Comment by felixfbecker** [comment]
Then this is not an issue with this library 😉
